/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LayoutRouteRouteImport } from './routes/_layout/route'
import { Route as LayoutIndexRouteImport } from './routes/_layout/index'
import { Route as ApiTargetRouteImport } from './routes/api/target'
import { Route as LayoutCartRouteImport } from './routes/_layout/cart'
import { Route as LayoutArtistRouteImport } from './routes/_layout/artist'
import { Route as ApiZqlReadRouteImport } from './routes/api/zql/read'
import { Route as ApiZeroQueryRouteImport } from './routes/api/zero/query'
import { Route as ApiZeroMutateRouteImport } from './routes/api/zero/mutate'
import { Route as ApiMutatorsSplatRouteImport } from './routes/api/mutators/$'
import { Route as ApiDirectReadRouteImport } from './routes/api/direct/read'
import { Route as ApiDemoStateRouteImport } from './routes/api/demo/state'
import { Route as ApiDemoResetRouteImport } from './routes/api/demo/reset'
import { Route as ApiDemoProtocolStateRouteImport } from './routes/api/demo/protocol-state'
import { Route as ApiDirectCartAddRouteImport } from './routes/api/direct/cart/add'

const LayoutRouteRoute = LayoutRouteRouteImport.update({
  id: '/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutIndexRoute = LayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutRouteRoute,
} as any)
const ApiTargetRoute = ApiTargetRouteImport.update({
  id: '/api/target',
  path: '/api/target',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutCartRoute = LayoutCartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => LayoutRouteRoute,
} as any)
const LayoutArtistRoute = LayoutArtistRouteImport.update({
  id: '/artist',
  path: '/artist',
  getParentRoute: () => LayoutRouteRoute,
} as any)
const ApiZqlReadRoute = ApiZqlReadRouteImport.update({
  id: '/api/zql/read',
  path: '/api/zql/read',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiZeroQueryRoute = ApiZeroQueryRouteImport.update({
  id: '/api/zero/query',
  path: '/api/zero/query',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiZeroMutateRoute = ApiZeroMutateRouteImport.update({
  id: '/api/zero/mutate',
  path: '/api/zero/mutate',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMutatorsSplatRoute = ApiMutatorsSplatRouteImport.update({
  id: '/api/mutators/$',
  path: '/api/mutators/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDirectReadRoute = ApiDirectReadRouteImport.update({
  id: '/api/direct/read',
  path: '/api/direct/read',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDemoStateRoute = ApiDemoStateRouteImport.update({
  id: '/api/demo/state',
  path: '/api/demo/state',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDemoResetRoute = ApiDemoResetRouteImport.update({
  id: '/api/demo/reset',
  path: '/api/demo/reset',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDemoProtocolStateRoute = ApiDemoProtocolStateRouteImport.update({
  id: '/api/demo/protocol-state',
  path: '/api/demo/protocol-state',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDirectCartAddRoute = ApiDirectCartAddRouteImport.update({
  id: '/api/direct/cart/add',
  path: '/api/direct/cart/add',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof LayoutIndexRoute
  '/artist': typeof LayoutArtistRoute
  '/cart': typeof LayoutCartRoute
  '/api/target': typeof ApiTargetRoute
  '/api/demo/protocol-state': typeof ApiDemoProtocolStateRoute
  '/api/demo/reset': typeof ApiDemoResetRoute
  '/api/demo/state': typeof ApiDemoStateRoute
  '/api/direct/read': typeof ApiDirectReadRoute
  '/api/mutators/$': typeof ApiMutatorsSplatRoute
  '/api/zero/mutate': typeof ApiZeroMutateRoute
  '/api/zero/query': typeof ApiZeroQueryRoute
  '/api/zql/read': typeof ApiZqlReadRoute
  '/api/direct/cart/add': typeof ApiDirectCartAddRoute
}
export interface FileRoutesByTo {
  '/artist': typeof LayoutArtistRoute
  '/cart': typeof LayoutCartRoute
  '/api/target': typeof ApiTargetRoute
  '/': typeof LayoutIndexRoute
  '/api/demo/protocol-state': typeof ApiDemoProtocolStateRoute
  '/api/demo/reset': typeof ApiDemoResetRoute
  '/api/demo/state': typeof ApiDemoStateRoute
  '/api/direct/read': typeof ApiDirectReadRoute
  '/api/mutators/$': typeof ApiMutatorsSplatRoute
  '/api/zero/mutate': typeof ApiZeroMutateRoute
  '/api/zero/query': typeof ApiZeroQueryRoute
  '/api/zql/read': typeof ApiZqlReadRoute
  '/api/direct/cart/add': typeof ApiDirectCartAddRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_layout': typeof LayoutRouteRouteWithChildren
  '/_layout/artist': typeof LayoutArtistRoute
  '/_layout/cart': typeof LayoutCartRoute
  '/api/target': typeof ApiTargetRoute
  '/_layout/': typeof LayoutIndexRoute
  '/api/demo/protocol-state': typeof ApiDemoProtocolStateRoute
  '/api/demo/reset': typeof ApiDemoResetRoute
  '/api/demo/state': typeof ApiDemoStateRoute
  '/api/direct/read': typeof ApiDirectReadRoute
  '/api/mutators/$': typeof ApiMutatorsSplatRoute
  '/api/zero/mutate': typeof ApiZeroMutateRoute
  '/api/zero/query': typeof ApiZeroQueryRoute
  '/api/zql/read': typeof ApiZqlReadRoute
  '/api/direct/cart/add': typeof ApiDirectCartAddRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/artist'
    | '/cart'
    | '/api/target'
    | '/api/demo/protocol-state'
    | '/api/demo/reset'
    | '/api/demo/state'
    | '/api/direct/read'
    | '/api/mutators/$'
    | '/api/zero/mutate'
    | '/api/zero/query'
    | '/api/zql/read'
    | '/api/direct/cart/add'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/artist'
    | '/cart'
    | '/api/target'
    | '/'
    | '/api/demo/protocol-state'
    | '/api/demo/reset'
    | '/api/demo/state'
    | '/api/direct/read'
    | '/api/mutators/$'
    | '/api/zero/mutate'
    | '/api/zero/query'
    | '/api/zql/read'
    | '/api/direct/cart/add'
  id:
    | '__root__'
    | '/_layout'
    | '/_layout/artist'
    | '/_layout/cart'
    | '/api/target'
    | '/_layout/'
    | '/api/demo/protocol-state'
    | '/api/demo/reset'
    | '/api/demo/state'
    | '/api/direct/read'
    | '/api/mutators/$'
    | '/api/zero/mutate'
    | '/api/zero/query'
    | '/api/zql/read'
    | '/api/direct/cart/add'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  LayoutRouteRoute: typeof LayoutRouteRouteWithChildren
  ApiTargetRoute: typeof ApiTargetRoute
  ApiDemoProtocolStateRoute: typeof ApiDemoProtocolStateRoute
  ApiDemoResetRoute: typeof ApiDemoResetRoute
  ApiDemoStateRoute: typeof ApiDemoStateRoute
  ApiDirectReadRoute: typeof ApiDirectReadRoute
  ApiMutatorsSplatRoute: typeof ApiMutatorsSplatRoute
  ApiZeroMutateRoute: typeof ApiZeroMutateRoute
  ApiZeroQueryRoute: typeof ApiZeroQueryRoute
  ApiZqlReadRoute: typeof ApiZqlReadRoute
  ApiDirectCartAddRoute: typeof ApiDirectCartAddRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof LayoutRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/': {
      id: '/_layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof LayoutIndexRouteImport
      parentRoute: typeof LayoutRouteRoute
    }
    '/api/target': {
      id: '/api/target'
      path: '/api/target'
      fullPath: '/api/target'
      preLoaderRoute: typeof ApiTargetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/cart': {
      id: '/_layout/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof LayoutCartRouteImport
      parentRoute: typeof LayoutRouteRoute
    }
    '/_layout/artist': {
      id: '/_layout/artist'
      path: '/artist'
      fullPath: '/artist'
      preLoaderRoute: typeof LayoutArtistRouteImport
      parentRoute: typeof LayoutRouteRoute
    }
    '/api/zql/read': {
      id: '/api/zql/read'
      path: '/api/zql/read'
      fullPath: '/api/zql/read'
      preLoaderRoute: typeof ApiZqlReadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/zero/query': {
      id: '/api/zero/query'
      path: '/api/zero/query'
      fullPath: '/api/zero/query'
      preLoaderRoute: typeof ApiZeroQueryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/zero/mutate': {
      id: '/api/zero/mutate'
      path: '/api/zero/mutate'
      fullPath: '/api/zero/mutate'
      preLoaderRoute: typeof ApiZeroMutateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/mutators/$': {
      id: '/api/mutators/$'
      path: '/api/mutators/$'
      fullPath: '/api/mutators/$'
      preLoaderRoute: typeof ApiMutatorsSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/direct/read': {
      id: '/api/direct/read'
      path: '/api/direct/read'
      fullPath: '/api/direct/read'
      preLoaderRoute: typeof ApiDirectReadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/demo/state': {
      id: '/api/demo/state'
      path: '/api/demo/state'
      fullPath: '/api/demo/state'
      preLoaderRoute: typeof ApiDemoStateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/demo/reset': {
      id: '/api/demo/reset'
      path: '/api/demo/reset'
      fullPath: '/api/demo/reset'
      preLoaderRoute: typeof ApiDemoResetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/demo/protocol-state': {
      id: '/api/demo/protocol-state'
      path: '/api/demo/protocol-state'
      fullPath: '/api/demo/protocol-state'
      preLoaderRoute: typeof ApiDemoProtocolStateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/direct/cart/add': {
      id: '/api/direct/cart/add'
      path: '/api/direct/cart/add'
      fullPath: '/api/direct/cart/add'
      preLoaderRoute: typeof ApiDirectCartAddRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface LayoutRouteRouteChildren {
  LayoutArtistRoute: typeof LayoutArtistRoute
  LayoutCartRoute: typeof LayoutCartRoute
  LayoutIndexRoute: typeof LayoutIndexRoute
}

const LayoutRouteRouteChildren: LayoutRouteRouteChildren = {
  LayoutArtistRoute: LayoutArtistRoute,
  LayoutCartRoute: LayoutCartRoute,
  LayoutIndexRoute: LayoutIndexRoute,
}

const LayoutRouteRouteWithChildren = LayoutRouteRoute._addFileChildren(
  LayoutRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  LayoutRouteRoute: LayoutRouteRouteWithChildren,
  ApiTargetRoute: ApiTargetRoute,
  ApiDemoProtocolStateRoute: ApiDemoProtocolStateRoute,
  ApiDemoResetRoute: ApiDemoResetRoute,
  ApiDemoStateRoute: ApiDemoStateRoute,
  ApiDirectReadRoute: ApiDirectReadRoute,
  ApiMutatorsSplatRoute: ApiMutatorsSplatRoute,
  ApiZeroMutateRoute: ApiZeroMutateRoute,
  ApiZeroQueryRoute: ApiZeroQueryRoute,
  ApiZqlReadRoute: ApiZqlReadRoute,
  ApiDirectCartAddRoute: ApiDirectCartAddRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
