// @generated drizzle-zero signature:sha256:39951f0b606cc90b1d05e632a3554625202ffaf6b44d979d22de07086d7b0cf0
// This file was automatically generated by drizzle-zero.
// You should NOT make any changes in this file as it will be overwritten.

import type { Row } from "@rocicorp/zero";
import { createBuilder } from "@rocicorp/zero";

const albumTable = {
  name: "album",
  columns: {
    id: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    artistId: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
      serverName: "artist_id",
    },
    title: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    year: {
      type: "number",
      optional: true,
      customType: null as unknown as number,
    },
  },
  primaryKey: ["id"],
} as const;
const artistTable = {
  name: "artist",
  columns: {
    id: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    name: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    sortName: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
      serverName: "sort_name",
    },
    type: {
      type: "string",
      optional: true,
      customType: null as unknown as string,
    },
    popularity: {
      type: "number",
      optional: true,
      customType: null as unknown as number,
    },
  },
  primaryKey: ["id"],
} as const;
const cartItemTable = {
  name: "cartItem",
  columns: {
    userId: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
      serverName: "user_id",
    },
    albumId: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
      serverName: "album_id",
    },
    addedAt: {
      type: "number",
      optional: false,
      customType: null as unknown as number,
      serverName: "added_at",
    },
  },
  primaryKey: ["userId", "albumId"],
  serverName: "cart_item",
} as const;
const albumRelationships = {
  artist: [
    { sourceField: ["artistId"], destField: ["id"], destSchema: "artist", cardinality: "one" },
  ],
  cartItems: [
    { sourceField: ["id"], destField: ["albumId"], destSchema: "cartItem", cardinality: "many" },
  ],
} as const;
const artistRelationships = {
  albums: [
    { sourceField: ["id"], destField: ["artistId"], destSchema: "album", cardinality: "many" },
  ],
} as const;
const cartItemRelationships = {
  album: [{ sourceField: ["albumId"], destField: ["id"], destSchema: "album", cardinality: "one" }],
} as const;
/**
 * The Zero schema object.
 * This type is auto-generated from your Drizzle schema definition.
 */
export const schema = {
  tables: {
    album: albumTable,
    artist: artistTable,
    cartItem: cartItemTable,
  },
  relationships: {
    album: albumRelationships,
    artist: artistRelationships,
    cartItem: cartItemRelationships,
  },
  enableLegacyQueries: false,
  enableLegacyMutators: false,
} as const;

/**
 * Represents the Zero schema type.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type Schema = typeof schema;
/**
 * Represents a row from the "album" table.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type Album = Row<(typeof schema)["tables"]["album"]>;
/**
 * Represents a row from the "artist" table.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type Artist = Row<(typeof schema)["tables"]["artist"]>;
/**
 * Represents a row from the "cartItem" table.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type CartItem = Row<(typeof schema)["tables"]["cartItem"]>;

/**
 * Represents the ZQL query builder.
 * This type is auto-generated from your Drizzle schema definition.
 */
export const zql = createBuilder(schema);
/**
 * Represents the Zero schema query builder.
 * This type is auto-generated from your Drizzle schema definition.
 */
export const builder = zql;

/** Defines the default types for Zero */
declare module "@rocicorp/zero" {
  interface DefaultTypes {
    schema: Schema;
  }
}
